@startuml uml-state-machine-uc-010
hide empty description
state "Displaying map with the fastest path to drivers destination from the current spot" as Map
state "Displaying map with the fastest path to drivers destination, while also showing the hitchhikers destination" as MapH
state "Show notification about nearby hitchhikers with their destination" as Notification
state "Confirm selected hitchhiker" as Confirm

[*] --> Map
Map --> Map : driver chooses different path
Map --> Notification
Notification --> Confirm : driver chose a hitchhiker
Confirm --> MapH
MapH --> Map : drop off hitchhiker
Map --> [*] : driver finishes driving
@enduml