@startuml
start
:System shows the fastest path to the drivers destination;
switch(Driver)
    case(Follows the path)
    :Driver drives their car towards the destination using the fastest path;
    case(Chooses a different path)
    :System shows a fastest path from the current spot;
    :Driver drives using the fastest path;
endswitch
repeat
:System shows notifications of awaiting hitchikers with similiar destinations as the drivers;
    switch(Driver)
    case(chooses to pick up a hitchhiker)
    :Driver picks up a hitchhiker on the road;
    :Driver drives to the hitchhikers destination (or closer to it);
    :Driver drops off the hitchhiker;
    case(chooses not to pick up a hitchhiker)
    endswitch
repeat while 
:Driver drives to their own destination;
:Driver finishes in their destination;
end
@enduml