@startuml
left to right direction
actor "Hitchhiker" as AC_H
actor "Driver" as AC_D
rectangle "E-Stop - Managing Rides" {
    usecase "Ride cancellation" as UC_RC
    usecase "Send notification on driver arrival" as UC_SNDA
    usecase "Report hitchhiker behaviour" as UC_RHB
}
AC_H --> UC_RC
AC_D --> UC_RC
AC_H --> UC_SNDA
AC_D --> UC_RHB
@enduml