@startuml
class User {
    given name
    email address
}

class Hitchhiker {
    preference: Preference [0..*]
}

class Driver {
    preference: Preference [0..*]
}

class Vehicle {
    hitchhiker capacity
}

class Ride {

}

class Destination {
}

class "Driver Rating" as DriverRating {
    score
    comment [0..1]
}

class Route {
    start: current location
    end: Destination
}

class "Driver Listing" as DriverListing {
    drivers: Driver [0..*]
}

class "Ride Request" as RideRequest {
    status
}

class Preference {

}

Driver -u-|> User
Hitchhiker -d-|> User

Driver "1" --> "0..*" DriverRating : receives ratings
Hitchhiker "1" --> "0..*" DriverRating : gives ratings

Driver "1" --> "0..*" RideRequest : receives
Hitchhiker "1" --> "0..*" RideRequest : issues

Driver "1" -r-> "0..1" Ride : provides
Hitchhiker "0..*" -r-> "0..1" Ride : uses

Driver "0..1" -l-> "1" Vehicle : drives
Driver "0..*" --> "0..1" Destination : specifies
Driver "0..*" --> "0..1" Route : follows
Driver "0..*" -l-> "1" DriverListing : included in

Hitchhiker "0..*" --> "0..1" Destination : specifies

Ride "0..*" --> "1" Route : follows
@enduml