@startuml
left to right direction
actor "Hitchhiker" as AC_H
rectangle "E-Stop - Establishing and Managing Rides" {
    usecase "Display driver listing" as UC_DDL
    usecase "Find available ride" as UC_FAR
}
UC_FAR .l.> UC_DDL : <<include>>
AC_H --> UC_DDL
AC_H --> UC_FAR
@enduml