@startuml
start
repeat
:System shows the fastest path to the drivers destination;
:System notifies driver, that a hitchiker in the area wants to use his ride;
switch(driver)
case(accepts)
:System shows the fastest path to the hitchhiker;
:Driver drives to the hitchhiker;
switch(driver)
case(drives to the hitchhiker)
:Driver picks up the hitchhiker;
:Driver drives the hitchiker closer to theirs destination;
:Driver drops off the hitchhiker closer to theirs destination;
case(cancels the drive)
endswitch
case(doesn't accept)
endswitch
repeat while
:Driver drives and finishes in their destination;
stop
@enduml